# Generated by Django 3.0.8 on 2020-07-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.URLField()),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=35, null=True)),
            ],
            options={
                'ordering': ('web_url',),
            },
        ),
    ]
